/**
 * Integration tests with Rasterio.
 *
 * Since rasterio is a Python library, we compare data indirectly via Numpy NPY
 * files. `geotiff-test-data` has a Pixi command named `generate-npy` that
 * generates NPY files from the same source GeoTIFFs
 */

import assert from "node:assert";
import { readFile } from "node:fs/promises";
import { TiffTag } from "@cogeotiff/core";
import { beforeAll, describe, expect, it } from "vitest";
import type { RasterArray, RasterTypedArray } from "../src/array.js";
import { toBandSeparate } from "../src/array.js";
import type { GeoTIFF } from "../src/geotiff.js";
import { fixturePath, loadGeoTIFF } from "./helpers.js";
import type { NPYTile } from "./utils/parse-npy.js";
import { parseNPY } from "./utils/parse-npy.js";

const FIXTURES = [
  { variant: "eox", name: "eox_cloudless" },
  { variant: "nlcd", name: "nlcd_landcover" },
  { variant: "rasterio", name: "cog_uint8_rgb_nodata" },
  { variant: "rasterio", name: "cog_uint8_rgb_mask" },
  { variant: "rasterio", name: "cog_uint8_rgba" },
  { variant: "rasterio", name: "float32_1band_lerc_block32" },
  { variant: "rasterio", name: "float32_1band_lerc_deflate_block32" },
  { variant: "rasterio", name: "float32_1band_lerc_zstd_block32" },

  { variant: "rasterio", name: "int8_3band_zstd_block64" },

  { variant: "rasterio", name: "uint16_1band_lzw_block128_predictor2" },
  { variant: "rasterio", name: "uint8_1band_and_alpha_deflate_block64_cog" },
  {
    variant: "rasterio",
    name: "uint8_1band_deflate_block128_unaligned_predictor2",
  },
  { variant: "rasterio", name: "uint8_1band_deflate_block128_unaligned" },
  // JPEG XL compression not supported
  // { variant: "rasterio", name: "uint8_1band_jxl_block64" },
  // LZMA compression not supported
  // { variant: "rasterio", name: "uint8_1band_lzma_block64" },
  { variant: "rasterio", name: "uint8_1band_lzw_block64_predictor2" },
  { variant: "rasterio", name: "uint8_nonrgb_deflate_block64_cog" },
  { variant: "rasterio", name: "uint8_rgb_deflate_block64_cog" },
  // WebP parsing uses canvas and is web-only
  // { variant: "rasterio", name: "uint8_rgb_webp_block64_cog" },
  // WebP parsing uses canvas and is web-only
  // { variant: "rasterio", name: "uint8_rgba_webp_block64_cog" },
  // JPEG parsing uses canvas and is web-only
  // { variant: "vantor", name: "maxar_opendata_yellowstone_visual" },
] as const;

/** Load a NPY tile from the same file, generated by rasterio. */
async function loadNpy(
  name: string,
  variant: string,
  {
    mask = false,
    z,
    x,
    y,
  }: {
    mask?: boolean;
    z: number;
    x: number;
    y: number;
  },
): Promise<NPYTile> {
  const maskString = mask ? "mask-" : "";
  const suffix = `/${maskString}${z}-${x}-${y}.npy`;
  const path = fixturePath(name, variant, suffix);
  const buffer = await readFile(path);
  const arrayBuffer = buffer.buffer.slice(
    buffer.byteOffset,
    buffer.byteOffset + buffer.byteLength,
  );
  return parseNPY(arrayBuffer);
}

/**
 * Convert pixel-interleaved `(height, width, bands)` to a flat band-major array
 * `(bands, height, width)`.
 *
 * This is equivalent to rasterio's `reshape_as_raster` function.
 */
function reshapeAsRaster(array: RasterArray): RasterTypedArray {
  const bandSep = toBandSeparate(array);
  const pixelCount = array.width * array.height;
  const Ctor = bandSep.bands[0]!.constructor as new (
    length: number,
  ) => RasterTypedArray;
  const out = new Ctor(array.count * pixelCount);
  for (let b = 0; b < array.count; b++) {
    out.set(bandSep.bands[b]!, b * pixelCount);
  }
  return out;
}

describe("tile data matches", () => {
  for (const { variant, name } of FIXTURES) {
    describe(`${variant}/${name}`, () => {
      let ours: GeoTIFF;

      beforeAll(async () => {
        ours = await loadGeoTIFF(name, variant);
      });

      it("tile pixel data matches", async () => {
        const { x: xTiles, y: yTiles } = ours.tileCount;
        for (let y = 0; y < yTiles; y++) {
          for (let x = 0; x < xTiles; x++) {
            const tile = await ours.fetchTile(x, y);

            const referenceData = await loadNpy(name, variant, { z: 0, x, y });

            const rasterOrderedData = reshapeAsRaster(tile.array);

            expect(rasterOrderedData.length).toBe(referenceData.data.length);
            expect(rasterOrderedData).toEqual(referenceData.data);

            const mask = tile.array.mask;
            if (mask !== null) {
              const referenceMask = await loadNpy(name, variant, {
                mask: true,
                z: 0,
                x,
                y,
              });

              expect(mask.length).toBe(referenceMask.data.length);
              expect(mask).toEqual(referenceMask.data);
            }
          }
        }
      });
    });
  }
});

// A custom test suite for maxar_opendata_yellowstone_visual because we can't
// decode JPEG data in Node. This is only for testing the mask data.
describe("Single-bit mask data", () => {
  describe(`maxar_opendata_yellowstone_visual`, async () => {
    const name = "maxar_opendata_yellowstone_visual";
    const variant = "vantor";
    const geotiff = await loadGeoTIFF(name, variant);

    const bitsPerSample = await geotiff.maskImage?.fetch(TiffTag.BitsPerSample);
    expect(bitsPerSample![0]).toEqual(1);

    it("tile mask data matches", async () => {
      const { x: xTiles, y: yTiles } = geotiff.tileCount;
      for (let y = 0; y < yTiles; y++) {
        for (let x = 0; x < xTiles; x++) {
          const tile = await geotiff.fetchTile(x, y);

          const mask = tile.array.mask;
          assert(mask !== null, "Expected mask to be present in this file");

          const referenceMask = await loadNpy(name, variant, {
            mask: true,
            z: 0,
            x,
            y,
          });

          expect(mask.length).toBe(referenceMask.data.length);
          expect(mask).toEqual(referenceMask.data);
        }
      }
    });
  });
});
