name: PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@fda730cb152c05a849d6d84325e50c6182d9d1e9 # 1.5.1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
